#!/bin/bash

CUDA_VISIBLE_DEVICES="" python main_ppo.py --n_node 10 --log_directory "store" --graph_mode "store" --graph_identifier "node_10_0" --num_stored_graphs 2000 --prop_stoch 0 --factor_inference_timesteps 1000
CUDA_VISIBLE_DEVICES="" python main_ppo.py --n_node 10 --log_directory "store" --graph_mode "store" --graph_identifier "node_10_0.2" --num_stored_graphs 2000 --prop_stoch 0.2 --factor_inference_timesteps 1000
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 10 --log_directory "final_10_0" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 3600 --clip_eps 0.2 --num_update_epochs 6 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.15 --ent_coeff 0.12 --graph_identifier "node_10_0" --prop_stoch 0 --deterministic_inference_policy True --num_stored_graphs 2000 --factor_inference_timesteps 1000
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 10 --log_directory "final_10_0.2" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 3600 --clip_eps 0.2 --num_update_epochs 6 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.15 --ent_coeff 0.12 --graph_identifier "node_10_0.2" --prop_stoch 0.2 --deterministic_inference_policy True --num_stored_graphs 2000 --factor_inference_timesteps 1000

#Train for 30 nodes 
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 30 --log_directory "final_node_30_0.4" --network_type "Big_CNN" --time_steps 15000000 --learning_rate 0.001 --num_steps_before_update 4800 --clip_eps 0.2 --num_update_epochs 6 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.15 --ent_coeff 0.12 --graph_identifier "node_30_relabel_0.4" --prop_stoch 0.4 --load_network_directory "node_30_relabel_0.4"
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 30 --log_directory "final_node_30_0.8" --network_type "Big_CNN" --time_steps 15000000 --learning_rate 0.001 --num_steps_before_update 4800 --clip_eps 0.2 --num_update_epochs 6 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.15 --ent_coeff 0.12 --graph_identifier "node_30_relabel_0.4" --prop_stoch 0.8 --load_network_directory "node_30_relabel_0.8"

CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 10 --log_directory "final_10_mixed_different_random_seed" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 3600 --clip_eps 0.2 --num_update_epochs 6 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.15 --ent_coeff 0.12 --graph_identifier "node_10_mixed" --deterministic_inference_policy True --num_stored_graphs 2000 --factor_inference_timesteps 1000 --random_seed_for_training 200 --random_seed_for_inference 201
