method: bayes               
metric:
  name: average_competitive_ratio    
  goal: minimize           
parameters:
  clip_eps:
    min: 0.1
    max: 0.2
  vf_coeff:
    min: 0.08
    max: 0.15
  ent_coeff:
    min: 0.1
    max: 0.3
  learning_rate:
    min: 0.0001
    max: 0.005
  num_update_epochs:
    distribution: q_uniform
    min: 4
    max: 10
    q: 2
  