method: bayes               
metric:
  name: average_competitive_ratio    
  goal: minimize           
parameters:
  clip_eps:
    min: 0.1
    max: 0.4
  vf_coeff:
    min: 0.05
    max: 0.2
  ent_coeff:
    min: 0.05
    max: 0.2
  learning_rate:
    min: 0.0001
    max: 0.01
  num_update_epochs:
    distribution: q_uniform
    min: 4
    max: 8
    q: 2
  num_steps_before_update:
    distribution: q_uniform
    min: 2400
    max: 3600
    q: 192
  ent_coeff_schedule:
    values: ["sigmoid","plateau"]