#10 nodes - 0.4
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 10 --log_directory "node_10_0.4_correct_testing" --time_steps 6000000 --network_type "Densenet_Same" --learning_rate 0.001 --num_steps_before_update 3600 --clip_eps 0.1 --num_update_epochs 7 --division_plateau 5 --ent_coeff_schedule "sigmoid" --vf_coeff 0.13 --ent_coeff 0.2 --deterministic_inference_policy True --graph_identifier "node_10_0.4_training_14k" --prop_stoch 0.4 --num_stored_graphs 14000 --factor_inference_timesteps 1000 --num_minibatches 2

#30 nodes
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 30 --log_directory "node_30_mixed_same_critic_narrow_densenet" --network_type "Densenet_Same" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 2000 --clip_eps 0.1 --num_update_epochs 10 --division_plateau 4 --ent_coeff_schedule "plateau" --vf_coeff 0.13 --ent_coeff 0.2 --graph_identifier "node_30_mixed" --prop_stoch 0.4 --num_minibatches 1 --horizon_length_factor 1 --densenet_growth_rate 20 --densenet_bn_size 2 --factor_inference_timesteps 1000
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 30 --log_directory "node_30_0.8_same_critic_narrow_densenet" --network_type "Densenet_Same" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 2000 --clip_eps 0.1 --num_update_epochs 10 --division_plateau 4 --ent_coeff_schedule "plateau" --vf_coeff 0.13 --ent_coeff 0.2 --graph_identifier "node_30_relabel_0.8" --prop_stoch 0.8 --num_minibatches 1 --horizon_length_factor 1 --densenet_growth_rate 20 --densenet_bn_size 2 --factor_inference_timesteps 500
CUDA_VISIBLE_DEVICES=0 python main_ppo.py --n_node 30 --log_directory "node_30_0.4_same_critic_narrow_densenet" --network_type "Densenet_Same" --time_steps 6000000 --learning_rate 0.001 --num_steps_before_update 2000 --clip_eps 0.1 --num_update_epochs 10 --division_plateau 4 --ent_coeff_schedule "plateau" --vf_coeff 0.13 --ent_coeff 0.2 --graph_identifier "node_30_relabel_0.4" --prop_stoch 0.4 --num_minibatches 1 --horizon_length_factor 1 --densenet_growth_rate 20 --densenet_bn_size 2 --factor_inference_timesteps 500


